//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblSertifikalarım
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Bu alan boş bırakılamaz!")]
        [StringLength(250, ErrorMessage = "En fazla 250 karakter olabilir!")]
        public string ACIKLAMA { get; set; }

        [Required(ErrorMessage = "Bu alan boş bırakılamaz!")]
        [StringLength(30, ErrorMessage = "En fazla 30 karakter olabilir!")]
        public string TARIH { get; set; }
    }
}
