//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblYeteneklerim
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz!")]
        [StringLength(100, ErrorMessage = "En fazla 100 karakter olabilir!")]
        public string YETENEK { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz!")]
        [Range(0, 100, ErrorMessage = "0-100 arasý bir deðer giriniz!")]
        public Nullable<byte> ORAN { get; set; }
    }
}
